# Generated by Django 6.0.5 on 2026-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mural/%Y/%m/', verbose_name='Imagem')),
                ('alt_texto', models.CharField(blank=True, help_text='Descreva a imagem para leitores de tela.', max_length=255, null=True, verbose_name='Texto Alternativo (acessibilidade)')),
                ('categoria', models.CharField(choices=[('camisas', 'Camisas'), ('calcas', 'Calças'), ('bermudas', 'Bermudas'), ('sapatos', 'Sapatos'), ('acessorios', 'Acessórios'), ('acessorios_metalicos', 'Acessórios Metálicos'), ('outros', 'Outros')], default='camisas', max_length=20, verbose_name='Categoria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
